import "./globals.css";
import type { Metadata } from "next";
import { Inter, Space_Mono } from "next/font/google";
import Nav from "@/components/Header";

const inter = Space_Mono({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} overflow-x-hidden bg-slate-900 text-white bg-no-repeat `}
			>
				<Nav />
				{children}
			</body>
		</html>
	);
}
